# Generated by Django 4.1.2 on 2022-10-18 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_shows_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shows',
            options={'ordering': ('-date',)},
        ),
    ]
