# Generated by Django 4.1.2 on 2022-10-19 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_venue_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='user',
        ),
    ]
